@extends(auth()->user()->role === 'super_admin' ? 'layouts.super_admin' : 'layouts.admin')

@section('content')

{{-- ADVANCED PRINT STYLESHEET --}}
<style>
    @media print {
        @page { size: portrait; margin: 15mm; }
        body { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; background: white !important; font-family: 'Helvetica', 'Arial', sans-serif; }
        
        /* Hide all web navigation, footers, buttons, and screen-only elements */
        aside, nav, footer, .no-print, header:not(.print-only) { display: none !important; }
        .print-only { display: block !important; }
        
        /* Reset container constraints to use full paper width */
        .max-w-7xl { max-width: 100% !important; padding: 0 !important; margin: 0 !important; }
        .print-shadow-none { box-shadow: none !important; border: 1px solid #e2e8f0 !important; border-radius: 0 !important; }
        .print-break-inside-avoid { break-inside: avoid; }
        
        /* Official DepEd Header Styling */
        .official-print-header { border-bottom: 4px double #1e293b; padding-bottom: 1rem; margin-bottom: 1.5rem; }
        .deped-red { color: #7f1d1d !important; } 

        /* Print Table Formatting */
        .print-table { width: 100% !important; border-collapse: collapse !important; border: none !important; }
        .print-table th { background-color: #f8fafc !important; padding: 8px !important; font-size: 10px !important; color: #475569 !important; border-bottom: 2px solid #cbd5e1 !important; text-transform: uppercase; letter-spacing: 0.05em; }
        .print-table td { padding: 8px !important; font-size: 10px !important; border-bottom: 1px solid #f1f5f9 !important; vertical-align: top !important; color: #1e293b !important; }
    }
    
    .print-only { display: none; }
</style>

<div class="max-w-7xl mx-auto px-4 py-8">

    {{-- 00. OFFICIAL DEPED PRINT HEADER (Visible on Paper Only) --}}
    <div class="print-only official-print-header">
        <div class="flex justify-between items-center mb-6">
            <div class="flex items-center gap-4">
                <img src="{{ asset('images/deped.png') }}" class="h-20 w-auto" alt="DepEd Logo">
                <div class="flex flex-col">
                    <span class="text-[9px] font-bold uppercase tracking-[0.3em] text-slate-800 leading-tight">Republic of the Philippines</span>
                    <h1 class="text-2xl font-black uppercase deped-red leading-tight tracking-tight">Department of Education</h1>
                    <p class="text-[10px] font-bold italic text-slate-600 uppercase tracking-widest mt-1">Division of Zamboanga City | Planning & Research Section</p>
                </div>
            </div>
            <div class="text-right flex flex-col items-end">
                <div class="border-2 border-slate-900 px-3 py-1.5 mb-2">
                    <span class="text-[9px] font-black uppercase tracking-[0.2em] text-slate-900 block leading-none">Document Control</span>
                    <span class="text-[12px] font-black deped-red uppercase tracking-widest block mt-1">Data Health Report</span>
                </div>
                <p class="text-[9px] font-mono font-bold text-slate-600 uppercase leading-none">Serial: HEALTH-{{ now()->format('Ymd') }}-{{ strtoupper(Str::random(4)) }}</p>
            </div>
        </div>

        <div class="flex justify-between items-end mt-6">
            <div>
                <h2 class="text-xl font-black uppercase tracking-tighter text-slate-900">Regional Risk Assessment Matrix</h2>
                <p class="text-[9px] text-slate-600 font-bold uppercase tracking-[0.2em] mt-1">
                    Generated By: {{ auth()->user()->name ?? 'System Administrator' }}
                </p>
            </div>
            <div class="text-right">
                <p class="text-[8px] font-black uppercase text-slate-500 tracking-widest">Date Generated</p>
                <p class="text-xs font-bold text-slate-900">{{ now()->format('F d, Y h:i A') }}</p>
            </div>
        </div>
    </div>

    {{-- 01. INTERFACE HEADER & MULTI-FILTER BAR (Hidden on Print) --}}
    <div class="mb-8 no-print">
        <div class="flex flex-col xl:flex-row justify-between items-end gap-6">
            <div>
                <span class="text-[10px] font-black text-red-800 uppercase tracking-[0.4em] mb-1 block">Executive Oversight</span>
                <h1 class="text-3xl font-black text-slate-800 uppercase tracking-tighter italic leading-none">Data Health & Hazard Audit</h1>
            </div>

            <form action="{{ route('admin.health_report') }}" method="GET" class="w-full xl:w-auto no-print">
                <div class="flex flex-wrap items-center gap-4 bg-white p-2 pl-6 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                    
                    <div class="flex items-center gap-3 flex-grow min-w-[240px] relative group">
                        <svg class="w-4 h-4 text-slate-300 group-focus-within:text-red-800 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                        </svg>
                        <input type="text" name="search" value="{{ request('search') }}" placeholder="Search institution ID or name..." class="w-full bg-transparent border-none py-2 text-xs font-bold text-slate-700 outline-none placeholder:text-slate-300 placeholder:font-medium">
                        
                        @if(request('search'))
                            <a href="{{ route('admin.health_report') }}" class="pr-2 text-slate-300 hover:text-red-800 transition-colors" title="Clear Search">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M6 18L18 6M6 6l12 12"/></svg>
                            </a>
                        @endif
                    </div>
                    
                    <button type="submit" style="background-color: #a52a2a;" class="text-white px-8 py-3 rounded-xl font-black uppercase text-[10px] tracking-[0.15em] hover:bg-red-900 transition-all shadow-lg shadow-red-900/20 active:scale-95">
                        Search
                    </button>
                </div>
            </form>

            <button onclick="window.print()" class="bg-[#1e293b] text-white px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-black transition-all flex items-center gap-2 shadow-sm shrink-0 no-print">
                <i class="bi bi-printer-fill text-sm"></i> Print Report
            </button>
        </div>
        
        <div class="mt-6 flex justify-end no-print">
            <div class="text-right">
                <span class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Flagged Institutions</span>
                <p class="text-2xl font-black text-slate-800 font-mono">
                    {{-- FIXED: Safely check if it's an object before checking for methods --}}
                    {{ is_object($flaggedSchools) && method_exists($flaggedSchools, 'total') ? $flaggedSchools->total() : count($flaggedSchools) }}
                </p>
            </div>
        </div>
    </div>

    {{-- 02. DATA HEALTH TABLE --}}
    <div class="bg-white rounded-[2.5rem] border border-slate-200 shadow-2xl shadow-slate-200/50 overflow-hidden print-shadow-none print-table">
        <table class="w-full text-left border-collapse print-table">
            <thead class="bg-slate-50 border-b border-slate-200 print:bg-slate-100">
                <tr class="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] print:text-slate-600">
                    <th class="p-8 print:py-2 print:px-2" style="width: 30%;">Institution</th>
                    <th class="p-8 print:py-2 print:px-2" style="width: 35%;">Physical Hazards</th>
                    <th class="p-8 print:py-2 print:px-2" style="width: 35%;">Resource Discrepancies</th>
                    <th class="p-8 text-center no-print">Protocol</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-100 print:divide-slate-200">
                @forelse($flaggedSchools as $data)
                    <tr class="group hover:bg-slate-50/50 transition-all print-break-inside-avoid">
                        {{-- Column 1: Institution --}}
                        <td class="p-8 print:py-3 print:px-2">
                            <span class="text-[10px] font-bold text-slate-400 block mb-1 print:text-[8px] print:text-slate-500 uppercase">ID: {{ $data['school']->school_id }}</span>
                            <p class="font-black text-slate-800 uppercase tracking-tight text-lg group-hover:text-red-800 transition-colors print:text-[10px] print:text-black">
                                {{ $data['school']->name }}
                            </p>
                        </td>

                        {{-- Column 2: Physical Hazard Status --}}
                        <td class="p-8 print:py-3 print:px-2">
                            @php
                                $rawHazards = is_array($data['school']->hazard_type) 
                                    ? $data['school']->hazard_type 
                                    : (json_decode($data['school']->hazard_type, true) ?? [$data['school']->hazard_type]);
                                
                                $activeHazards = [];
                                if (is_array($rawHazards)) {
                                    foreach($rawHazards as $h) {
                                        $clean = trim(str_replace(['"', '[', ']'], '', (string)$h));
                                        if (!empty($clean) && strtolower($clean) !== 'none' && strtolower($clean) !== 'others') {
                                            $activeHazards[] = $clean;
                                        }
                                    }
                                }
                                $hazardSeverity = count($activeHazards) > 1 ? 'High' : 'Moderate';
                            @endphp

                            @if(count($activeHazards) > 0)
                                <div class="inline-flex flex-col gap-2">
                                    <span class="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-slate-700 print:text-[9px] print:text-black">
                                        <span class="w-2 h-2 rounded-full no-print {{ $hazardSeverity === 'High' ? 'bg-red-600 animate-pulse' : 'bg-amber-500' }}"></span>
                                        <strong class="print-only">TYPE: </strong> {{ implode(', ', $activeHazards) }}
                                    </span>
                                    <span class="px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-tighter w-fit print:px-0 print:py-0 print:border-none print:text-black print:bg-transparent
                                        {{ $hazardSeverity === 'High' ? 'bg-red-100 text-red-700 border border-red-200' : 'bg-amber-100 text-amber-700 border border-amber-200' }}">
                                        Severity: {{ $hazardSeverity }}
                                    </span>
                                </div>
                            @else
                                <span class="text-[10px] font-black text-slate-300 uppercase italic tracking-widest print:text-[9px] print:text-slate-500">No Physical Hazard</span>
                            @endif
                        </td>

                        {{-- Column 3: Resource Ratio Issues --}}
                        <td class="p-8 print:py-3 print:px-2">
                            <div class="space-y-2">
                                @forelse($data['issues'] as $issue)
                                    <div class="flex items-start gap-2 text-[10px] font-bold text-slate-500 uppercase leading-tight print:text-[9px] print:text-black">
                                        <span class="text-red-500 print:text-black">⚠</span>
                                        {{ $issue }}
                                    </div>
                                @empty
                                    <span class="text-[10px] font-black text-slate-300 uppercase italic tracking-widest print:text-[9px] print:text-slate-500">Resources Stable</span>
                                @endforelse
                            </div>
                        </td>

                        {{-- Column 4: Action (Hidden on Print) --}}
                        <td class="p-8 text-center no-print">
                            <a href="{{ route('schools.edit', $data['school']->id) }}" class="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-slate-100 text-slate-800 hover:bg-red-800 hover:text-white transition-all shadow-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-5M16.5 3.5a2.121 2.121 0 013 3L7 19l-4 1 1-4L16.5 3.5z" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="p-32 print:p-10 text-center">
                            <div class="flex flex-col items-center gap-4">
                                <div class="w-16 h-16 bg-emerald-50 text-emerald-500 rounded-full flex items-center justify-center text-2xl font-bold no-print">✓</div>
                                <p class="text-xs text-slate-400 uppercase font-black tracking-[0.3em]">All Institutions Clear of Hazards</p>
                            </div>
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        {{-- PAGINATION (FIXED: Safely check if it's an object before checking for methods) --}}
        @if(is_object($flaggedSchools) && method_exists($flaggedSchools, 'hasPages') && $flaggedSchools->hasPages())
            <div class="p-6 bg-slate-50 border-t border-slate-200 no-print">
                {{ $flaggedSchools->appends(request()->query())->links() }}
            </div>
        @endif
    </div>

    {{-- 03. OFFICIAL VALIDATION FOOTER (Visible on Paper Only) --}}
    <div class="print-only mt-12 print-break-inside-avoid">
        <div class="flex justify-between items-end px-8">
            <div class="text-center w-64">
                <div class="border-b-2 border-slate-900 mb-2 h-10"></div>
                <p class="text-[9px] font-black uppercase tracking-widest text-slate-900">Certified Correct By:</p>
                <p class="text-[8px] text-slate-600 font-bold uppercase mt-1">Division Planning Officer</p>
            </div>
            <div class="text-center w-64">
                <div class="border-b-2 border-slate-900 mb-2 h-10"></div>
                <p class="text-[9px] font-black uppercase tracking-widest text-slate-900">Noted By:</p>
                <p class="text-[8px] text-slate-600 font-bold uppercase mt-1">Schools Division Superintendent</p>
            </div>
        </div>
        
        <div class="mt-12 flex flex-col items-center gap-1.5 border-t border-slate-300 pt-4">
            <p class="text-[8px] font-black text-slate-500 uppercase tracking-[0.5em]">End of Regional Risk Assessment Matrix</p>
            <p class="text-[7px] text-slate-500 italic font-mono">System-generated verifiable document. E-Code: {{ strtoupper(Str::random(16)) }}</p>
        </div>
    </div>

</div>
@endsection