@extends('layouts.super_admin')

@section('content')

{{-- ADVANCED PRINT STYLESHEET --}}
<style>
    @media print {
        /* Set to Portrait Document Form */
        @page { size: portrait; margin: 15mm; }
        body { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; background: white !important; font-family: 'Helvetica', 'Arial', sans-serif; }
        
        /* Hide all web navigation, footers, buttons, and screen-only elements */
        aside, nav, footer, .no-print, header:not(.print-only) { display: none !important; }
        .print-only { display: block !important; }
        
        /* Reset container constraints to use full paper width */
        .max-w-7xl { max-width: 100% !important; padding: 0 !important; margin: 0 !important; }
        .print-shadow-none { box-shadow: none !important; border: 1px solid #e2e8f0 !important; border-radius: 0 !important; }
        .print-break-inside-avoid { break-inside: avoid; }
        
        /* Official DepEd Header Styling */
        .official-print-header { border-bottom: 4px double #1e293b; padding-bottom: 1rem; margin-bottom: 1.5rem; }
        .deped-red { color: #7f1d1d !important; } 

        /* Print Table Formatting (Adjusted smaller for Portrait Width) */
        .print-table { width: 100% !important; border-collapse: collapse !important; border: none !important; }
        .print-table th { background-color: #f8fafc !important; padding: 8px !important; font-size: 10px !important; color: #475569 !important; border-bottom: 2px solid #cbd5e1 !important; text-transform: uppercase; letter-spacing: 0.05em; }
        .print-table td { padding: 8px !important; font-size: 10px !important; border-bottom: 1px solid #f1f5f9 !important; vertical-align: top !important; color: #1e293b !important; }
    }
    
    .print-only { display: none; }
</style>

<div class="max-w-7xl mx-auto px-4 py-8">

    {{-- 00. OFFICIAL DEPED PRINT HEADER (Visible on Paper Only) --}}
    <div class="print-only official-print-header">
        <div class="flex justify-between items-center mb-6">
            <div class="flex items-center gap-4">
                <img src="{{ asset('images/deped.png') }}" class="h-20 w-auto" alt="DepEd Logo">
                <div class="flex flex-col">
                    <span class="text-[9px] font-bold uppercase tracking-[0.3em] text-slate-800 leading-tight">Republic of the Philippines</span>
                    <h1 class="text-2xl font-black uppercase deped-red leading-tight tracking-tight">Department of Education</h1>
                    <p class="text-[10px] font-bold italic text-slate-600 uppercase tracking-widest mt-1">Division of Zamboanga City | System Administration</p>
                </div>
            </div>
            <div class="text-right flex flex-col items-end">
                <div class="border-2 border-slate-900 px-3 py-1.5 mb-2">
                    <span class="text-[9px] font-black uppercase tracking-[0.2em] text-slate-900 block leading-none">Document Control</span>
                    <span class="text-[12px] font-black deped-red uppercase tracking-widest block mt-1">Audit Ledger</span>
                </div>
                <p class="text-[9px] font-mono font-bold text-slate-600 uppercase leading-none">Serial: AUDIT-{{ now()->format('Ymd') }}-{{ strtoupper(Str::random(4)) }}</p>
            </div>
        </div>

        <div class="flex justify-between items-end mt-6">
            <div>
                <h2 class="text-xl font-black uppercase tracking-tighter text-slate-900">Master System Audit Log</h2>
                <p class="text-[9px] text-slate-600 font-bold uppercase tracking-[0.2em] mt-1">
                    Generated By: {{ auth()->user()->name ?? 'System Administrator' }}
                </p>
            </div>
            <div class="text-right">
                <p class="text-[8px] font-black uppercase text-slate-500 tracking-widest">Date Generated</p>
                <p class="text-xs font-bold text-slate-900">{{ now()->format('F d, Y h:i A') }}</p>
            </div>
        </div>
    </div>

    {{-- 01. INTERFACE HEADER & MULTI-FILTER BAR (Hidden on Print) --}}
    <div class="mb-8 no-print flex flex-col gap-5">
        
        {{-- Top Row: Title and Print Action --}}
        <div class="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
            <div>
                <span class="text-[10px] font-black text-red-800 uppercase tracking-[0.4em] mb-1 block">Master Audit Log</span>
                <h1 class="text-3xl font-black text-slate-800 uppercase tracking-tighter italic leading-none">System History</h1>
            </div>
            <button onclick="window.print()" class="bg-[#1e293b] text-white px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-black transition-all flex items-center gap-2 shadow-sm shrink-0">
                <i class="bi bi-printer-fill text-sm"></i> Print Ledger
            </button>
        </div>

        {{-- Bottom Row: Structured Search and Filters --}}
        <form action="{{ route('superadmin.history') }}" method="GET" class="flex flex-col lg:flex-row gap-3 w-full items-center bg-slate-50 p-2 lg:p-3 rounded-[1.5rem] border border-slate-200 shadow-sm">
            
            {{-- Search Bar --}}
            <div class="relative flex-1 w-full flex items-center bg-white border border-slate-200 rounded-xl focus-within:border-[#a52a2a] focus-within:ring-1 focus-within:ring-[#a52a2a] transition-all shadow-sm px-4 py-2">
                <svg class="w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                </svg>
                <input type="text" name="search" value="{{ request('search') }}" placeholder="Search account, action, or target..." class="w-full bg-transparent border-none text-xs font-bold text-slate-700 px-3 py-1 outline-none placeholder:text-slate-300 placeholder:font-medium">
            </div>

            {{-- Date Range Filters --}}
            <div class="flex items-center gap-2 w-full lg:w-auto bg-white border border-slate-200 rounded-xl p-1.5 shadow-sm shrink-0">
                <div class="flex items-center gap-2 px-3 py-1.5 bg-slate-50 rounded-lg w-full lg:w-auto">
                    <span class="text-[8px] font-black text-slate-400 uppercase tracking-widest">From</span>
                    <input type="date" name="from_date" value="{{ request('from_date') }}" class="bg-transparent border-none text-[10px] font-black text-slate-600 outline-none cursor-pointer w-full">
                </div>
                <span class="text-slate-300 font-bold">-</span>
                <div class="flex items-center gap-2 px-3 py-1.5 bg-slate-50 rounded-lg w-full lg:w-auto">
                    <span class="text-[8px] font-black text-slate-400 uppercase tracking-widest">To</span>
                    <input type="date" name="to_date" value="{{ request('to_date') }}" class="bg-transparent border-none text-[10px] font-black text-slate-600 outline-none cursor-pointer w-full">
                </div>
            </div>

            {{-- Action Buttons --}}
            <div class="flex items-center gap-2 w-full lg:w-auto shrink-0">
                <button type="submit" style="background-color: #a52a2a;" class="flex-1 lg:flex-none text-white px-8 py-3 rounded-xl font-black uppercase text-[10px] tracking-widest hover:bg-red-900 transition-all shadow-md active:scale-95 text-center">
                    Filter
                </button>

                @if(request()->anyFilled(['from_date', 'to_date', 'search']))
                    <a href="{{ route('superadmin.history') }}" class="flex items-center justify-center bg-slate-200 text-slate-500 hover:text-red-700 hover:bg-red-100 px-4 py-3 rounded-xl transition-colors" title="Clear Filters">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M6 18L18 6M6 6l12 12"/></svg>
                    </a>
                @endif
            </div>
        </form>
    </div>

    {{-- 02. ACTIVITY LEDGER TABLE --}}
    <div class="bg-white rounded-[2.5rem] border border-slate-200 shadow-2xl shadow-slate-200/50 overflow-hidden print-shadow-none print-table">
        <table class="w-full text-left border-collapse print-table">
            <thead class="bg-slate-50 border-b border-slate-200 print:bg-slate-100">
                <tr class="text-[10px] font-black text-slate-400 uppercase tracking-widest print:text-slate-600">
                    <th class="p-5 print:py-2 print:px-2" style="width: 16%;">Date & Time</th>
                    <th class="p-5 print:py-2 print:px-2" style="width: 20%;">Account Name</th>
                    <th class="p-5 print:py-2 print:px-2" style="width: 14%;">System Role</th>
                    <th class="p-5 print:py-2 print:px-2" style="width: 50%;">Action & Modifications</th>
                </tr>
            </thead>
            <tbody class="text-xs font-bold divide-y divide-slate-100 print:divide-slate-200">
                @forelse($logs as $log)
                <tr class="hover:bg-slate-50/50 transition-colors print-break-inside-avoid">
                    
                    {{-- COLUMN 1: DATE & TIME --}}
                    <td class="p-5 print:py-3 print:px-2">
                        <div class="text-slate-600 font-mono text-[11px] print:text-[10px] print:text-black">
                            {{ $log->created_at->format('M d, Y') }}
                        </div>
                        <div class="text-[9px] opacity-60 text-slate-400 print:text-[8px] print:text-slate-500 mt-0.5">
                            {{ $log->created_at->format('h:i A') }}
                        </div>
                    </td>
                    
                    {{-- COLUMN 2: ACCOUNT NAME --}}
                    <td class="p-5 print:py-3 print:px-2 uppercase text-slate-800 print:text-[9px] print:text-black font-black">
                        {{ $log->user->name ?? 'System/Unknown' }}
                    </td>
                    
                    {{-- COLUMN 3: ROLE --}}
                    <td class="p-5 print:py-3 print:px-2">
                        <?php $role = $log->user->role ?? 'unknown'; ?>
                        @if($role === 'super_admin')
                            <span class="bg-red-50 text-red-800 px-2.5 py-1 rounded-md text-[9px] font-black uppercase tracking-widest border border-red-200 print:bg-transparent print:border-none print:p-0 print:text-[#991b1b] print:text-[8px]">
                                Super Admin
                            </span>
                        @elseif($role === 'admin')
                            <span class="bg-blue-50 text-blue-800 px-2.5 py-1 rounded-md text-[9px] font-black uppercase tracking-widest border border-blue-200 print:bg-transparent print:border-none print:p-0 print:text-[#1e40af] print:text-[8px]">
                                Admin
                            </span>
                        @else
                            <span class="bg-slate-100 text-slate-800 px-2.5 py-1 rounded-md text-[9px] font-black uppercase tracking-widest print:bg-transparent print:border-none print:p-0 print:text-[#374151] print:text-[8px]">
                                {{ str_replace('_', ' ', $role) }}
                            </span>
                        @endif
                    </td>

                    {{-- COLUMN 4: ACTION & MODIFICATIONS --}}
                    <td class="p-5 print:py-3 print:px-2">
                        
                        {{-- SCREEN VIEW --}}
                        <div class="mb-2 no-print">
                            <span class="text-red-800 font-black uppercase tracking-wider text-[11px]">{{ $log->action }}</span>
                            <span class="text-slate-300 mx-1">|</span>
                            <span class="text-slate-600 font-bold uppercase text-[10px]">{{ $log->target_name }}</span>
                        </div>
                        
                        <details class="group cursor-pointer no-print">
                            <summary class="list-none text-[9px] font-black text-slate-400 uppercase tracking-widest hover:text-slate-800 transition-colors inline-flex items-center gap-1">
                                <span>Show Data Changes</span>
                                <svg class="w-3 h-3 transition-transform group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                            </summary>
                            <div class="mt-2 p-3 bg-slate-50/80 rounded-xl text-left border border-slate-200/60 shadow-inner">
                                <div class="text-[10px] text-slate-600 font-mono">
                                    @if(isset($log->changes['before']))
                                        <ul class="list-none pl-0 space-y-1.5">
                                            @foreach($log->changes['before'] as $key => $oldValue)
                                                <?php 
                                                    $newValue = isset($log->changes['after'][$key]) ? $log->changes['after'][$key] : $oldValue; 
                                                    $oldStr = is_array($oldValue) ? json_encode($oldValue) : (string)$oldValue;
                                                    $newStr = is_array($newValue) ? json_encode($newValue) : (string)$newValue;
                                                ?>
                                                @if($oldStr !== $newStr)
                                                    <li class="flex items-start gap-2">
                                                        <span class="font-bold text-slate-800 uppercase min-w-[100px]">{{ str_replace('_', ' ', $key) }}:</span> 
                                                        <div class="flex-1 flex items-center gap-2 flex-wrap">
                                                            <span class="text-red-500 line-through bg-red-50 px-1 rounded">{{ $oldStr ?: 'Empty' }}</span> 
                                                            <span class="text-slate-300">→</span> 
                                                            <span class="text-green-600 font-bold bg-green-50 px-1 rounded">{{ $newStr ?: 'Empty' }}</span>
                                                        </div>
                                                    </li>
                                                @endif
                                            @endforeach
                                        </ul>
                                    @elseif(!empty($log->changes) && (is_array($log->changes) || is_object($log->changes)))
                                        <ul class="list-none pl-0 space-y-1.5">
                                            @foreach($log->changes as $key => $value)
                                                @if(!is_array($value))
                                                    <li class="flex items-start gap-2">
                                                        <span class="font-bold text-slate-800 uppercase min-w-[100px]">{{ str_replace('_', ' ', $key) }}:</span> 
                                                        <span class="text-slate-700 bg-white px-1.5 rounded border border-slate-100">{{ $value }}</span>
                                                    </li>
                                                @endif
                                            @endforeach
                                        </ul>
                                    @else
                                        <span class="italic text-slate-400">No specific data changes recorded.</span>
                                    @endif
                                </div>
                            </div>
                        </details>

                        {{-- PRINT VIEW (Formatted Beautifully for Portrait Paper) --}}
                        <div class="print-only text-black">
                            <div style="margin-bottom: 4px;">
                                <strong style="font-size: 8px; color: #64748b; letter-spacing: 0.1em; text-transform: uppercase;">Action:</strong> 
                                <span style="text-transform: uppercase; color: #991b1b; font-weight: 900; margin-left: 2px;">{{ $log->action }}</span>
                            </div>
                            <div style="margin-bottom: 6px;">
                                <strong style="font-size: 8px; color: #64748b; letter-spacing: 0.1em; text-transform: uppercase;">Target:</strong> 
                                <span style="text-transform: uppercase; color: #1e293b; font-weight: 900; margin-left: 2px;">{{ $log->target_name }}</span>
                            </div>

                            @if(isset($log->changes['before']) || (!empty($log->changes) && is_array($log->changes)))
                                <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 6px; mt-1">
                                    <strong style="font-size: 8px; color: #475569; text-transform: uppercase; letter-spacing: 0.1em; border-bottom: 1px solid #cbd5e1; display: block; padding-bottom: 2px; margin-bottom: 4px;">Data Modifications</strong>
                                    <ul style="margin: 0; padding: 0; list-style: none; font-size: 9px;">
                                        @if(isset($log->changes['before']))
                                            @foreach($log->changes['before'] as $key => $oldValue)
                                                <?php 
                                                    $newValue = isset($log->changes['after'][$key]) ? $log->changes['after'][$key] : $oldValue; 
                                                    $oldStr = is_array($oldValue) ? json_encode($oldValue) : (string)$oldValue;
                                                    $newStr = is_array($newValue) ? json_encode($newValue) : (string)$newValue;
                                                ?>
                                                @if($oldStr !== $newStr)
                                                    <li style="margin-bottom: 3px; display: flex; align-items: flex-start; gap: 4px;">
                                                        <strong style="text-transform: uppercase; color: #334155; width: 85px; flex-shrink: 0; font-size: 8px;">{{ str_replace('_', ' ', $key) }}:</strong>
                                                        <div style="flex-grow: 1; display: flex; flex-wrap: wrap; gap: 3px; align-items: center;">
                                                            <span style="color: #94a3b8; text-decoration: line-through;">{{ $oldStr ?: 'Empty' }}</span> 
                                                            <span style="color: #cbd5e1;">&rarr;</span> 
                                                            <strong style="color: #15803d;">{{ $newStr ?: 'Empty' }}</strong>
                                                        </div>
                                                    </li>
                                                @endif
                                            @endforeach
                                        @elseif(is_array($log->changes) || is_object($log->changes))
                                            @foreach($log->changes as $key => $value)
                                                @if(!is_array($value))
                                                    <li style="margin-bottom: 3px; display: flex; align-items: flex-start; gap: 4px;">
                                                        <strong style="text-transform: uppercase; color: #334155; width: 85px; flex-shrink: 0; font-size: 8px;">{{ str_replace('_', ' ', $key) }}:</strong> 
                                                        <strong style="color: #1e293b;">{{ $value }}</strong>
                                                    </li>
                                                @endif
                                            @endforeach
                                        @endif
                                    </ul>
                                </div>
                            @else
                                <div style="font-style: italic; color: #94a3b8; font-size: 9px; margin-top: 6px;">
                                    No detailed data changes recorded.
                                </div>
                            @endif
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="p-20 print:p-10 text-center text-slate-300 uppercase font-black tracking-[0.5em] text-xs">
                        No activity found for selected criteria
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>

        {{-- PAGINATION --}}
        @if($logs->hasPages())
            <div class="p-6 bg-slate-50 border-t border-slate-200 no-print">
                {{ $logs->links() }}
            </div>
        @endif
    </div>

    {{-- 04. OFFICIAL VALIDATION FOOTER (Visible on Paper Only) --}}
    <div class="print-only mt-12 print-break-inside-avoid">
        <div class="flex justify-between items-end px-8">
            <div class="text-center w-64">
                <div class="border-b-2 border-slate-900 mb-2 h-10"></div>
                <p class="text-[9px] font-black uppercase tracking-widest text-slate-900">Certified Correct By:</p>
                <p class="text-[8px] text-slate-600 font-bold uppercase mt-1">System Administrator</p>
            </div>
            <div class="text-center w-64">
                <div class="border-b-2 border-slate-900 mb-2 h-10"></div>
                <p class="text-[9px] font-black uppercase tracking-widest text-slate-900">Noted By:</p>
                <p class="text-[8px] text-slate-600 font-bold uppercase mt-1">Schools Division Superintendent</p>
            </div>
        </div>
        
        <div class="mt-12 flex flex-col items-center gap-1.5 border-t border-slate-300 pt-4">
            <p class="text-[8px] font-black text-slate-500 uppercase tracking-[0.5em]">End of Official System Audit Log</p>
            <p class="text-[7px] text-slate-500 italic font-mono">System-generated verifiable document. E-Code: {{ strtoupper(Str::random(16)) }}</p>
        </div>
    </div>

</div>
@endsection