@extends('layouts.super_admin')

@section('content')

{{-- 00. OFFICIAL PRINT HEADER (DepEd Letterhead Style) --}}
<div class="hidden print:block mb-6">
    <div class="text-center border-b-[3px] border-black pb-4 mb-4">
        <img src="{{ asset('images/deped_zambo_header.png') }}" class="mx-auto" style="height: 80px; object-fit: contain;" alt="DepEd Header">
        <h1 class="text-2xl font-black uppercase tracking-widest mt-4">Master System Audit Ledger</h1>
    </div>
    <div class="flex justify-between text-[10px] font-bold uppercase tracking-widest text-slate-800">
        <p>GENERATED BY: {{ auth()->user()->name ?? 'SUPER ADMIN' }}</p>
        <div class="text-right">
            <p>DOC REF: MASTER-LOG-{{ strtoupper(Str::random(8)) }}</p>
            <p>DATE: {{ now()->format('m/d/Y h:i A') }}</p>
        </div>
    </div>
</div>

<div class="max-w-7xl mx-auto px-4">
    {{-- 01. INTERFACE HEADER & MULTI-FILTER BAR --}}
    <div class="mb-8 no-print">
        <div class="flex flex-col xl:flex-row justify-between items-end gap-6">
            <div>
                <span class="text-[10px] font-black text-red-800 uppercase tracking-[0.4em] mb-1 block">Master Audit Log</span>
                <h1 class="text-3xl font-black text-slate-800 uppercase tracking-tighter italic leading-none">System History</h1>
                
            </div>

            <form action="{{ route('superadmin.history') }}" method="GET" class="w-full xl:w-auto no-print">
                <div class="flex flex-wrap items-center gap-4 bg-white p-2 pl-6 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                    
                    <div class="flex items-center gap-3 flex-grow min-w-[240px] relative group">
                        <svg class="w-4 h-4 text-slate-300 group-focus-within:text-red-800 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                        </svg>
                        <input type="text" name="search" value="{{ request('search') }}" placeholder="Search account, action, or target..." class="w-full bg-transparent border-none py-2 text-xs font-bold text-slate-700 outline-none placeholder:text-slate-300 placeholder:font-medium">
                        
                        @if(request('search'))
                            <a href="{{ route('superadmin.history') }}" class="pr-2 text-slate-300 hover:text-red-800 transition-colors" title="Clear Search">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M6 18L18 6M6 6l12 12"/></svg>
                            </a>
                        @endif
                    </div>

                    <div class="h-8 w-px bg-slate-100 hidden lg:block"></div>

                    <div class="flex items-center gap-2">
                        <div class="flex items-center gap-2 px-3 py-1.5 bg-slate-50 rounded-xl border border-transparent focus-within:border-slate-200 transition-all">
                            <span class="text-[8px] font-black text-slate-400 uppercase tracking-widest">From</span>
                            <input type="date" name="from_date" value="{{ request('from_date') }}" class="bg-transparent border-none text-[10px] font-black text-slate-600 outline-none cursor-pointer">
                        </div>
                        <svg class="w-3 h-3 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M13 7l5 5-5 5M6 7l5 5-5 5"/>
                        </svg>
                        <div class="flex items-center gap-2 px-3 py-1.5 bg-slate-50 rounded-xl border border-transparent focus-within:border-slate-200 transition-all">
                            <span class="text-[8px] font-black text-slate-400 uppercase tracking-widest">To</span>
                            <input type="date" name="to_date" value="{{ request('to_date') }}" class="bg-transparent border-none text-[10px] font-black text-slate-600 outline-none cursor-pointer">
                        </div>
                    </div>

                    @if(request()->anyFilled(['from_date', 'to_date']))
                        <a href="{{ route('superadmin.history') }}" class="p-2 mr-2 text-slate-300 hover:text-red-800 transition-all" title="Reset All Filters">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                        </a>
                    @endif
                    
                    <button type="submit" style="background-color: #a52a2a;" class="text-white px-8 py-3 rounded-xl font-black uppercase text-[10px] tracking-[0.15em] hover:bg-red-900 transition-all shadow-lg shadow-red-900/20 active:scale-95">
                        Filter
                    </button>
                </div>
            </form>

            <button onclick="window.print()" class="bg-white border border-slate-300 text-slate-600 px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:border-slate-800 transition-all flex items-center gap-2 shadow-sm shrink-0">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                Export Ledger
            </button>
        </div>
    </div>

    {{-- 02. ACTIVITY LEDGER TABLE --}}
    <div class="bg-white rounded-[2rem] border border-slate-200 shadow-xl overflow-hidden print:border-none print:shadow-none print:rounded-none">
        <table class="w-full text-left border-collapse">
            <thead class="bg-slate-50 border-b border-slate-200">
                <tr class="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                    <th class="p-5 print:p-3" style="width: 15%;">Date & Time</th>
                    <th class="p-5 print:p-3" style="width: 25%;">Account Name</th>
                    <th class="p-5 print:p-3" style="width: 15%;">System Role</th>
                    <th class="p-5 print:p-3" style="width: 45%;">Action & Modifications</th>
                </tr>
            </thead>
            <tbody class="text-xs font-bold divide-y divide-slate-100">
                @forelse($logs as $log)
                <tr class="hover:bg-slate-50/50 transition-colors">
                    
                    {{-- COLUMN 1: DATE & TIME --}}
                    <td class="p-5 print:p-3">
                        <div class="text-slate-600 font-mono text-[11px] print:text-[10px] print:text-black print:font-bold">
                            {{ $log->created_at->format('M d, Y') }}
                        </div>
                        <div class="text-[9px] opacity-60 text-slate-400 print:text-black mt-0.5 print:text-[9px]">
                            {{ $log->created_at->format('h:i A') }}
                        </div>
                    </td>
                    
                    {{-- COLUMN 2: ACCOUNT NAME --}}
                    <td class="p-5 print:p-3 uppercase text-slate-800 print:text-[10px] print:font-bold">
                        {{ $log->user->name ?? 'System/Unknown' }}
                    </td>
                    
                    {{-- COLUMN 3: ROLE --}}
                    <td class="p-5 print:p-3">
                        <?php $role = $log->user->role ?? 'unknown'; ?>
                        @if($role === 'super_admin')
                            <span class="bg-red-50 text-red-800 px-2.5 py-1 rounded-md text-[9px] font-black uppercase tracking-widest border border-red-200 print:bg-transparent print:border-none print:p-0 print:text-[10px] print:text-black print:font-bold">
                                Super Admin
                            </span>
                        @elseif($role === 'admin')
                            <span class="bg-blue-50 text-blue-800 px-2.5 py-1 rounded-md text-[9px] font-black uppercase tracking-widest border border-blue-200 print:bg-transparent print:border-none print:p-0 print:text-[10px] print:text-black print:font-bold">
                                Admin
                            </span>
                        @else
                            <span class="bg-slate-100 text-slate-800 px-2.5 py-1 rounded-md text-[9px] font-black uppercase tracking-widest print:bg-transparent print:border-none print:p-0 print:text-[10px] print:text-black print:font-bold">
                                {{ $role }}
                            </span>
                        @endif
                    </td>

                    {{-- COLUMN 4: ACTION & MODIFICATIONS --}}
                    <td class="p-5 print:p-3">
                        
                        {{-- SCREEN VIEW --}}
                        <div class="mb-2 print:hidden">
                            <span class="text-red-800 font-black uppercase tracking-wider text-[11px]">{{ $log->action }}</span>
                            <span class="text-slate-300 mx-1">|</span>
                            <span class="text-slate-600 font-bold uppercase text-[10px]">{{ $log->target_name }}</span>
                        </div>
                        
                        <details class="group cursor-pointer no-print">
                            <summary class="list-none text-[9px] font-black text-slate-400 uppercase tracking-widest hover:text-slate-800 transition-colors inline-flex items-center gap-1">
                                <span>Show Data Changes</span>
                                <svg class="w-3 h-3 transition-transform group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                            </summary>
                            <div class="mt-2 p-3 bg-slate-50/80 rounded-xl text-left border border-slate-200/60 shadow-inner">
                                <div class="text-[10px] text-slate-600 font-mono">
                                    @if(isset($log->changes['before']))
                                        <ul class="list-none pl-0 space-y-1.5">
                                            @foreach($log->changes['before'] as $key => $oldValue)
                                                <?php $newValue = isset($log->changes['after'][$key]) ? $log->changes['after'][$key] : $oldValue; ?>
                                                @if((string)$oldValue !== (string)$newValue)
                                                    <li class="flex items-start gap-2">
                                                        <span class="font-bold text-slate-800 uppercase min-w-[100px]">{{ str_replace('_', ' ', $key) }}:</span> 
                                                        <div class="flex-1 flex items-center gap-2 flex-wrap">
                                                            <span class="text-red-500 line-through bg-red-50 px-1 rounded">{{ is_array($oldValue) ? json_encode($oldValue) : ($oldValue ?: 'Empty') }}</span> 
                                                            <span class="text-slate-300">→</span> 
                                                            <span class="text-green-600 font-bold bg-green-50 px-1 rounded">{{ is_array($newValue) ? json_encode($newValue) : ($newValue ?: 'Empty') }}</span>
                                                        </div>
                                                    </li>
                                                @endif
                                            @endforeach
                                        </ul>
                                    @elseif(!empty($log->changes) && (is_array($log->changes) || is_object($log->changes)))
                                        <ul class="list-none pl-0 space-y-1.5">
                                            @foreach($log->changes as $key => $value)
                                                @if(!is_array($value))
                                                    <li class="flex items-start gap-2">
                                                        <span class="font-bold text-slate-800 uppercase min-w-[100px]">{{ str_replace('_', ' ', $key) }}:</span> 
                                                        <span class="text-slate-700 bg-white px-1.5 rounded border border-slate-100">{{ $value }}</span>
                                                    </li>
                                                @endif
                                            @endforeach
                                        </ul>
                                    @else
                                        <span class="italic text-slate-400">No specific data changes recorded.</span>
                                    @endif
                                </div>
                            </div>
                        </details>

                        {{-- PRINT VIEW --}}
                        <div class="hidden print:block text-[10px] text-black">
                            <div style="margin-bottom: 4px;">
                                <strong>ACTION:</strong> <span style="text-transform: uppercase;">{{ $log->action }}</span>
                            </div>
                            <div style="margin-bottom: 6px;">
                                <strong>TARGET:</strong> <span style="text-transform: uppercase;">{{ $log->target_name }}</span>
                            </div>

                            @if(isset($log->changes['before']) || (!empty($log->changes) && is_array($log->changes)))
                                <div style="border-top: 1px dashed #ccc; padding-top: 6px; margin-top: 6px;">
                                    <strong style="font-size: 9px; color: #444;">MODIFICATIONS RECORDED:</strong>
                                    <ul style="margin: 4px 0 0 16px; padding: 0; list-style-type: square;">
                                        @if(isset($log->changes['before']))
                                            @foreach($log->changes['before'] as $key => $oldValue)
                                                <?php $newValue = isset($log->changes['after'][$key]) ? $log->changes['after'][$key] : $oldValue; ?>
                                                @if((string)$oldValue !== (string)$newValue)
                                                    <li style="margin-bottom: 3px;">
                                                        <span style="text-transform: uppercase;">{{ str_replace('_', ' ', $key) }}</span>: 
                                                        <span style="color: #555;">{{ $oldValue ?: 'Empty' }}</span> &rarr; 
                                                        <strong>{{ $newValue ?: 'Empty' }}</strong>
                                                    </li>
                                                @endif
                                            @endforeach
                                        @elseif(is_array($log->changes) || is_object($log->changes))
                                            @foreach($log->changes as $key => $value)
                                                @if(!is_array($value))
                                                    <li style="margin-bottom: 3px;">
                                                        <span style="text-transform: uppercase;">{{ str_replace('_', ' ', $key) }}</span>: 
                                                        <strong>{{ $value }}</strong>
                                                    </li>
                                                @endif
                                            @endforeach
                                        @endif
                                    </ul>
                                </div>
                            @else
                                <div style="border-top: 1px dashed #ccc; padding-top: 4px; margin-top: 4px; font-style: italic; color: #666; font-size: 9px;">
                                    No specific data changes recorded.
                                </div>
                            @endif
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="p-20 text-center text-slate-300 uppercase font-black tracking-[0.5em] text-xs">
                        No activity found for selected criteria
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>

        {{-- PAGINATION --}}
        @if($logs->hasPages())
            <div class="p-6 bg-slate-50 border-t border-slate-200 no-print">
                {{ $logs->links() }}
            </div>
        @endif
    </div>
</div>
@endsection